name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/sss-action@v.0.1.2
    - name: Deploy NodeJS app
      with:
         host: ${{secrets.SSH_HOST}} # IP address of the server to ssh into
         key: ${{secrets.SSH_KEY}} # key of the server
         username: ${{secrets.SSH_USERNAME}} # user of the server
         
         script: |
           mkdir test
           cs test
           git clone git@github.com:MayaKroft/CD.git
           echo 'Deployment successful to digital ocean'
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
