name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/sss-action@v.0.1.2
    - name: Deploy NodeJS app
      with:
         host: ${{secrets.SSH_HOST}} # IP address of the server to ssh into
         key: ${{secrets.SSH_KEY}} # key of the server
         username: ${{secrets.SSH_USERNAME}} # user of the server
         
         script: |
           mkdir test
           cs test
           git clone git@github.com:MayaKroft/CD.git
           echo 'Deployment successful to digital ocean'
  
