name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@v0.1.2
      with:
         host: ${{secrets.SSH_HOST}} # IP address of the server to ssh into
         key: ${{secrets.SSH_KEY}} # key of the server
         username: ${{secrets.SSH_USERNAME}} # user of the server
         password: ${{secrets.SSH_PASSWORD}} # password of the user
         passphrase: ${{secrets.SSH_PASSPHRASE}} #passphrase for the key
         
         script: |
           sudo mkdir test
           cd test
           sudo git clone git@github.com:MayaKroft/CD.git
           echo 'Deployment successful to digital ocean'
           
  
